- name: copy zabbix package to all nodes
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: root
    force: yes
    mode: 755
  with_items:
    - {src: "./zabbix_agentd.conf", dest: "/opt/"}
    - {src: "./zabbix-agent-4.0.9-3.el7.x86_64.rpm", dest: "/opt/"}

- name: install zabbix
  shell: "{{item}}"
  with_items:
    - "rpm -ivh /opt/zabbix-agent-4.0.9-3.el7.x86_64.rpm --force"
    - "cp /opt/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.conf"
    - "systemctl enable zabbix-agent"
    - "systemctl start zabbix-agent"

- name: clean zabbix package
  shell: "{{item}}"
  with_items:
    - "rm -rf /opt/zabbix_agentd.conf"
    - "rm -rf /opt/zabbix-agent-4.0.9-3.el7.x86_64.rpm"
